In [2]:
import numpy as np

In [2]:
# criando array 1D
l = [1,2,3]
x = np.array(l)
print("x:", x)
print("Shape: ",x.shape)

x: [1 2 3]
Shape:  (3,)


In [3]:
#Array 2 d: Listas aninhadas
l=[[1,2],[3,4]]
x = np.array(l)
print("x:\n",x)
print("shape: ",x.shape)

x:
 [[1 2]
 [3 4]]
shape:  (2, 2)


In [6]:
# array contendo apenas 0's
dim =(2,2) #linhas e colunas
x = np.zeros(dim)
print("x:\n", x)
print("shape: ", x.shape)


x:
 [[0. 0.]
 [0. 0.]]
shape:  (2, 2)


In [7]:
# array contendo apenas 1's
size =(2,2) #linhas e colunas
x = np.ones(size)
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[1. 1.]
 [1. 1.]]
shape:  (2, 2)


In [8]:
#criação de valores dentro de um intervalo
#valores uniformes entre 5 e 15
x_min,x_max =5,15
x = np.linspace(start=x_min, stop=x_max,num=6)
print("x:\n",x)
print("shape: ",x.shape)

x:
 [ 5.  7.  9. 11. 13. 15.]
shape:  (6,)


In [9]:
#criação de matriz identidade
n=4
x = np.eye(n)
print("x:\n",x)
print("Shape: ",x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape:  (4, 4)


In [12]:
#criação de valores  aleatórios
#np.random.seed(10)
x=np.random.random(size=(2,3))
print("x:\n",x)
print("shape:",x.shape)

x:
 [[0.5074331  0.1109494  0.19181865]
 [0.80449587 0.0139045  0.63618153]]
shape: (2, 3)


Indexação de arrays

In [3]:
# indices de 0 a n-1
x = np.linspace(start=10, stop=100, num=10)
print("x:",x)
print("shape:", x.shape)

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [4]:
#extração de elementos
print("x: ", x)
print("primeiro elemento", x[0])
print("segundo elemento ", x[1])
print("ultimo elemento: ", x[-1])

x:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento 10.0
segundo elemento  20.0
ultimo elemento:  100.0


In [6]:
#slicing: extração de subarrays
print("x: ",x)
print("dois primeiros elementos: ", x[0:2])
print("dois  primeiros elementos: ", x[:2])
print("dois ultimos elementos ", x[-2:])

x:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos:  [10. 20.]
dois  primeiros elementos:  [10. 20.]
dois ultimos elementos  [ 90. 100.]


In [9]:
#slincing de array 2d
x= x.reshape(2,5) # reshape de x para 2 linhas e 5 colunas
print("X ", x)

X  [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [10]:
#extração de elementos
print("primeira linha, segunda coluna :", x[0,1])
print("segunda linha, penultima coluna: ", x[1,-2])
print("!ultima linha, ultima coluna ", x[1,4])
print("!ultima linha, ultima coluna", x[-1, -1])

primeira linha, segunda coluna : 20.0
segunda linha, penultima coluna:  90.0
!ultima linha, ultima coluna  100.0
!ultima linha, ultima coluna 100.0


In [11]:
#slicing para sub-arrays
print("x:", x )
print("primeira linha inteia ", x[0,:])
print("primeira linha, segunda a quarta coluna ", x[0,1:4])
print("ultima coluna inteira: ",x[:,[-1]])

x: [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
primeira linha inteia  [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna  [20. 30. 40.]
ultima coluna inteira:  [[ 50.]
 [100.]]


ATENÇÃO COM COMPARTILHAMENTO DE MEMORIA COM SUBARRAYS

In [14]:
x = np.array([1,2,3])
print("x antes:", x)
y = x[:2]
y[0] = -100 #alterando valor em y altera o valor de x
print("x depois:",x)

x antes: [1 2 3]
x depois: [-100    2    3]


In [15]:
x = np.array([1,2,3])
print("x antes:", x)
y = x[:2].copy()
y[0] = -100 #alterando valor em y altera o valor de x
print("x depois:",x)

x antes: [1 2 3]
x depois: [1 2 3]
