In [1]:
import numpy as np

In [2]:
x  = np.array([[1,2],[3,4]])
y = np.array([1.3 , 3.5])
print(x)
print(y)

[[1 2]
 [3 4]]
[1.3 3.5]


In [3]:
#comparação ponto a ponto
print("comparação de um array com um escalar > :\n", x>2 )
print("comparação de um array com um escalar >= :\n",x >=2 )
print("comparação de um array com um escalar < :\n", x <2)
print("comparação de um array com um escalar  <=:\n", x <=2)
print("comparação entre arrays == \n", x ==y )
print("comparação entre arrays > \n",x >x )
print("comparação entre arrays  \n",x >y )# briadcasting

comparação de um array com um escalar > :
 [[False False]
 [ True  True]]
comparação de um array com um escalar >= :
 [[False  True]
 [ True  True]]
comparação de um array com um escalar < :
 [[ True False]
 [False False]]
comparação de um array com um escalar  <=:
 [[ True  True]
 [False False]]
comparação entre arrays == 
 [[False False]
 [False False]]
comparação entre arrays > 
 [[False False]
 [False False]]
comparação entre arrays  
 [[False False]
 [ True  True]]


INDEXAÇÃO BOOLEANA

In [4]:
#indexação booelana
x  = np.array([[1,3,7],
               [4,11,21],
               [42,8,9]
              ])
print("x: \n",x)

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [5]:
#indexação booleana> retornar o número de elementos
# maiores que k
k = 10
cond = x  >  k
print("condição: n", cond)
print(f"elementos maiores que {k}: \n",len(x[cond]) )

condição: n [[False False False]
 [False  True  True]
 [ True False False]]
elementos maiores que 10: 
 3


In [6]:
#indexação booleana: extração de números pares
cond = x % 2 == 0 
print("condição : \n", cond)
print("Números pares :\n", x[cond])

condição : 
 [[False False False]
 [ True False False]
 [ True  True False]]
Números pares :
 [ 4 42  8]


In [8]:
#indexação booleana: extração de números ímpares
cond = x % 2 == 1 
print("condição : \n", cond)
print("Números ímpares :\n", x[cond])

condição : 
 [[ True  True  True]
 [False  True  True]
 [False False  True]]
Números ímpares :
 [ 1  3  7 11 21  9]
