funções aritméticas


In [1]:
import numpy as np

In [2]:
# criando 2 arrays #broadcasting
x = np.ones((2,2))
y = np.eye(2)
print("x : \n", x)
print("y : \n",y)

x : 
 [[1. 1.]
 [1. 1.]]
y : 
 [[1. 0.]
 [0. 1.]]


In [3]:
#soma
print(" soma de arrays \n", x+y )
print("com float ou int  \n", x+2)

 soma de arrays 
 [[2. 1.]
 [1. 2.]]
com float ou int  
 [[3. 3.]
 [3. 3.]]


In [4]:
#subtração
print(" subtração \n,", x-y )
print("com float ou int \n",x-2 )

 subtração 
, [[0. 1.]
 [1. 0.]]
com float ou int 
 [[-1. -1.]
 [-1. -1.]]


In [5]:
print(" divisao  \n", x/y )
print("com float \n", x/2 )

 divisao  
 [[ 1. inf]
 [inf  1.]]
com float 
 [[0.5 0.5]
 [0.5 0.5]]


C:\Users\aecle\AppData\Local\Temp\ipykernel_4972\1600535081.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print(" divisao  \n", x/y )


In [6]:
# vai dar errado
np.array([1,2,3]) + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
#varias operações
print("combinando operação:\n", (x+y)  / (x-2))

In [7]:
print(x)
print(y)

[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]


In [9]:
#multiplicação
print("multiplicação de arrays \n", x *y)
print("multiplicando por int/float \n", x *2)

multiplicação de arrays 
 [[1. 0.]
 [0. 1.]]
multiplicando por int/float 
 [[2. 2.]
 [2. 2.]]


In [10]:
#multiplicação matricial
print("multiplicação matricial (np.dot):\n", np.dot(x,y))
print("multiplicação matricial (@):\n", x @ y)
print("multiplicação matricial (.dot):\n", x.dot(y))

multiplicação matricial (np.dot):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (@):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (.dot):
 [[1. 1.]
 [1. 1.]]


In [12]:
"""
Exemplo:
solução de um sistema de equações:
x +2*b =7
3*a - 2*b = -11
solução analitica : (a,b) = (-1,4)

matricialmente, este problema tem a seguinte solução

    Ax = c, onde:
    - x = [a,b]
    - A = [[1,2], [3,-2]]
    - c = [7, -11]
    solução numerica x = inv(A) @ c,
"""
#definição do problema
A =  np.array([[1,2], [3, -2]])
C = np.array([[7], [-11]])
print("A : \n", A)
print("C : \n", C)


A : 
 [[ 1  2]
 [ 3 -2]]
C : 
 [[  7]
 [-11]]


In [13]:
x =  np.dot(np.linalg.inv(A),C)
x = np.linalg.inv(A) @ C